WIP: Have the ability to print JSON, but need to test ability to prin…
ericdrosado/Elixir-Client pull request #1
Opened 2018-06-05 12:51 UTC by ericdrosado

…t a server directory without using a real server.

2018-06-07 01:48 UTC, cdemyanovich requested changes

2018-06-07 01:48 UTC, cdemyanovich commented on README.md
> ++ Swift 1.6.4+
Should "Swift" be "Elixir"?

2018-06-07 01:50 UTC, cdemyanovich commented on README.md
> ++ In the root directory: `./elixir_client --host=https://erosado-swift-server.herokuapp.com`
I got this error when running:
```
➜  Elixir-Client git:(communicate_with_server) ✗ ./elixir_client --host=https://erosado-swift-server.herokuapp.com
** (KeyError) key :body not found in: %HTTPoison.Error{id: nil, reason: :timeout}
    (elixir_client) lib/client/client.ex:5: Client.get/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

2018-06-07 01:50 UTC, cdemyanovich commented on README.md
> ++ In the root directory `mix escript.build`.
Why are there changes after I compile?
```
➜  Elixir-Client git:(communicate_with_server) ✗ git st
On branch communicate_with_server
Your branch is up to date with 'origin/communicate_with_server'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   elixir_client

no changes added to commit (use "git add" and/or "git commit -a")
➜  Elixir-Client git:(communicate_with_server) ✗
```

2020-02-26 17:09 UTC, tommcgee requested changes
Can't get this out of my pending PR reviews! Hope all is well!

2020-02-27 02:06 UTC, ericdrosado commented
> Can't get this out of my pending PR reviews! Hope all is well!

Whoops! Sorry about that @tommcgee !

I hope all is well.

2020-02-27 02:06 UTC, closed without merging